// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalksApi.Data;

#nullable disable

namespace NZWalksApi.Data.Migrations
{
    [DbContext(typeof(NZWalksDBContext))]
    [Migration("20240826122354_Foo")]
    partial class Foo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalksApi.Data.Entities.RegionEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BeautyGrade")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BeautyGrade = 1,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8761),
                            Description = "Description for region 1",
                            Name = "Region 1",
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8810)
                        },
                        new
                        {
                            ID = 2,
                            BeautyGrade = 3,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8818),
                            Description = "Description for region 2",
                            Name = "Region 2",
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8819)
                        },
                        new
                        {
                            ID = 3,
                            BeautyGrade = 3,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8821),
                            Description = "Description for region 3",
                            Name = "Region 3",
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8822)
                        },
                        new
                        {
                            ID = 4,
                            BeautyGrade = 2,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8825),
                            Description = "Description for region 4",
                            Name = "Region 4",
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8826)
                        },
                        new
                        {
                            ID = 5,
                            BeautyGrade = 3,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8829),
                            Description = "Description for region 5",
                            Name = "Region 5",
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8830)
                        },
                        new
                        {
                            ID = 6,
                            BeautyGrade = 2,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8834),
                            Description = "Description for region 6",
                            Name = "Region 6",
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8835)
                        },
                        new
                        {
                            ID = 7,
                            BeautyGrade = 1,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8836),
                            Description = "Description for region 7",
                            Name = "Region 7",
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8837)
                        },
                        new
                        {
                            ID = 8,
                            BeautyGrade = 3,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8839),
                            Description = "Description for region 8",
                            Name = "Region 8",
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8839)
                        },
                        new
                        {
                            ID = 9,
                            BeautyGrade = 3,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8841),
                            Description = "Description for region 9",
                            Name = "Region 9",
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8842)
                        },
                        new
                        {
                            ID = 10,
                            BeautyGrade = 0,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8846),
                            Description = "Description for region 10",
                            Name = "Region 10",
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8847)
                        });
                });

            modelBuilder.Entity("NZWalksApi.Data.Entities.WalkEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RegionID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("RegionID");

                    b.ToTable("Walks");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8961),
                            Description = "Description for walk 1",
                            LengthInKm = 13.0,
                            Name = "Walk 1",
                            RegionID = 9,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8963)
                        },
                        new
                        {
                            ID = 2,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8967),
                            Description = "Description for walk 2",
                            LengthInKm = 17.0,
                            Name = "Walk 2",
                            RegionID = 6,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8968)
                        },
                        new
                        {
                            ID = 3,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8970),
                            Description = "Description for walk 3",
                            LengthInKm = 7.0,
                            Name = "Walk 3",
                            RegionID = 3,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8971)
                        },
                        new
                        {
                            ID = 4,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8973),
                            Description = "Description for walk 4",
                            LengthInKm = 12.0,
                            Name = "Walk 4",
                            RegionID = 1,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8974)
                        },
                        new
                        {
                            ID = 5,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8976),
                            Description = "Description for walk 5",
                            LengthInKm = 12.0,
                            Name = "Walk 5",
                            RegionID = 5,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(8976)
                        },
                        new
                        {
                            ID = 6,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9003),
                            Description = "Description for walk 6",
                            LengthInKm = 3.0,
                            Name = "Walk 6",
                            RegionID = 1,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9004)
                        },
                        new
                        {
                            ID = 7,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9006),
                            Description = "Description for walk 7",
                            LengthInKm = 4.0,
                            Name = "Walk 7",
                            RegionID = 10,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9006)
                        },
                        new
                        {
                            ID = 8,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9008),
                            Description = "Description for walk 8",
                            LengthInKm = 4.0,
                            Name = "Walk 8",
                            RegionID = 9,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9009)
                        },
                        new
                        {
                            ID = 9,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9011),
                            Description = "Description for walk 9",
                            LengthInKm = 9.0,
                            Name = "Walk 9",
                            RegionID = 3,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9012)
                        },
                        new
                        {
                            ID = 10,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9015),
                            Description = "Description for walk 10",
                            LengthInKm = 13.0,
                            Name = "Walk 10",
                            RegionID = 10,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9016)
                        },
                        new
                        {
                            ID = 11,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9018),
                            Description = "Description for walk 11",
                            LengthInKm = 9.0,
                            Name = "Walk 11",
                            RegionID = 4,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9018)
                        },
                        new
                        {
                            ID = 12,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9020),
                            Description = "Description for walk 12",
                            LengthInKm = 15.0,
                            Name = "Walk 12",
                            RegionID = 6,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9021)
                        },
                        new
                        {
                            ID = 13,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9023),
                            Description = "Description for walk 13",
                            LengthInKm = 15.0,
                            Name = "Walk 13",
                            RegionID = 2,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9024)
                        },
                        new
                        {
                            ID = 14,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9026),
                            Description = "Description for walk 14",
                            LengthInKm = 10.0,
                            Name = "Walk 14",
                            RegionID = 7,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9026)
                        },
                        new
                        {
                            ID = 15,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9028),
                            Description = "Description for walk 15",
                            LengthInKm = 9.0,
                            Name = "Walk 15",
                            RegionID = 8,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9029)
                        },
                        new
                        {
                            ID = 16,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9031),
                            Description = "Description for walk 16",
                            LengthInKm = 13.0,
                            Name = "Walk 16",
                            RegionID = 1,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9031)
                        },
                        new
                        {
                            ID = 17,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9033),
                            Description = "Description for walk 17",
                            LengthInKm = 9.0,
                            Name = "Walk 17",
                            RegionID = 4,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9034)
                        },
                        new
                        {
                            ID = 18,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9037),
                            Description = "Description for walk 18",
                            LengthInKm = 2.0,
                            Name = "Walk 18",
                            RegionID = 1,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9038)
                        },
                        new
                        {
                            ID = 19,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9040),
                            Description = "Description for walk 19",
                            LengthInKm = 9.0,
                            Name = "Walk 19",
                            RegionID = 10,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9040)
                        },
                        new
                        {
                            ID = 20,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9042),
                            Description = "Description for walk 20",
                            LengthInKm = 18.0,
                            Name = "Walk 20",
                            RegionID = 9,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9043)
                        },
                        new
                        {
                            ID = 21,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9045),
                            Description = "Description for walk 21",
                            LengthInKm = 6.0,
                            Name = "Walk 21",
                            RegionID = 10,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9045)
                        },
                        new
                        {
                            ID = 22,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9047),
                            Description = "Description for walk 22",
                            LengthInKm = 10.0,
                            Name = "Walk 22",
                            RegionID = 4,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9048)
                        },
                        new
                        {
                            ID = 23,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9050),
                            Description = "Description for walk 23",
                            LengthInKm = 10.0,
                            Name = "Walk 23",
                            RegionID = 9,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9051)
                        },
                        new
                        {
                            ID = 24,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9052),
                            Description = "Description for walk 24",
                            LengthInKm = 11.0,
                            Name = "Walk 24",
                            RegionID = 1,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9053)
                        },
                        new
                        {
                            ID = 25,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9055),
                            Description = "Description for walk 25",
                            LengthInKm = 4.0,
                            Name = "Walk 25",
                            RegionID = 9,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9056)
                        },
                        new
                        {
                            ID = 26,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9057),
                            Description = "Description for walk 26",
                            LengthInKm = 12.0,
                            Name = "Walk 26",
                            RegionID = 3,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9058)
                        },
                        new
                        {
                            ID = 27,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9060),
                            Description = "Description for walk 27",
                            LengthInKm = 10.0,
                            Name = "Walk 27",
                            RegionID = 6,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9061)
                        },
                        new
                        {
                            ID = 28,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9062),
                            Description = "Description for walk 28",
                            LengthInKm = 12.0,
                            Name = "Walk 28",
                            RegionID = 3,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9063)
                        },
                        new
                        {
                            ID = 29,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9065),
                            Description = "Description for walk 29",
                            LengthInKm = 8.0,
                            Name = "Walk 29",
                            RegionID = 8,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9066)
                        },
                        new
                        {
                            ID = 30,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9068),
                            Description = "Description for walk 30",
                            LengthInKm = 10.0,
                            Name = "Walk 30",
                            RegionID = 4,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9068)
                        },
                        new
                        {
                            ID = 31,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9070),
                            Description = "Description for walk 31",
                            LengthInKm = 13.0,
                            Name = "Walk 31",
                            RegionID = 4,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9071)
                        },
                        new
                        {
                            ID = 32,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9073),
                            Description = "Description for walk 32",
                            LengthInKm = 17.0,
                            Name = "Walk 32",
                            RegionID = 9,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9074)
                        },
                        new
                        {
                            ID = 33,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9075),
                            Description = "Description for walk 33",
                            LengthInKm = 13.0,
                            Name = "Walk 33",
                            RegionID = 8,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9076)
                        },
                        new
                        {
                            ID = 34,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9079),
                            Description = "Description for walk 34",
                            LengthInKm = 14.0,
                            Name = "Walk 34",
                            RegionID = 4,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9080)
                        },
                        new
                        {
                            ID = 35,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9081),
                            Description = "Description for walk 35",
                            LengthInKm = 17.0,
                            Name = "Walk 35",
                            RegionID = 9,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9082)
                        },
                        new
                        {
                            ID = 36,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9084),
                            Description = "Description for walk 36",
                            LengthInKm = 2.0,
                            Name = "Walk 36",
                            RegionID = 6,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9084)
                        },
                        new
                        {
                            ID = 37,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9086),
                            Description = "Description for walk 37",
                            LengthInKm = 2.0,
                            Name = "Walk 37",
                            RegionID = 4,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9087)
                        },
                        new
                        {
                            ID = 38,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9089),
                            Description = "Description for walk 38",
                            LengthInKm = 17.0,
                            Name = "Walk 38",
                            RegionID = 1,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9089)
                        },
                        new
                        {
                            ID = 39,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9091),
                            Description = "Description for walk 39",
                            LengthInKm = 10.0,
                            Name = "Walk 39",
                            RegionID = 3,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9092)
                        },
                        new
                        {
                            ID = 40,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9094),
                            Description = "Description for walk 40",
                            LengthInKm = 8.0,
                            Name = "Walk 40",
                            RegionID = 7,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9095)
                        },
                        new
                        {
                            ID = 41,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9096),
                            Description = "Description for walk 41",
                            LengthInKm = 18.0,
                            Name = "Walk 41",
                            RegionID = 1,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9097)
                        },
                        new
                        {
                            ID = 42,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9099),
                            Description = "Description for walk 42",
                            LengthInKm = 13.0,
                            Name = "Walk 42",
                            RegionID = 1,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9100)
                        },
                        new
                        {
                            ID = 43,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9102),
                            Description = "Description for walk 43",
                            LengthInKm = 9.0,
                            Name = "Walk 43",
                            RegionID = 8,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9102)
                        },
                        new
                        {
                            ID = 44,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9104),
                            Description = "Description for walk 44",
                            LengthInKm = 14.0,
                            Name = "Walk 44",
                            RegionID = 2,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9105)
                        },
                        new
                        {
                            ID = 45,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9121),
                            Description = "Description for walk 45",
                            LengthInKm = 14.0,
                            Name = "Walk 45",
                            RegionID = 5,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9122)
                        },
                        new
                        {
                            ID = 46,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9124),
                            Description = "Description for walk 46",
                            LengthInKm = 10.0,
                            Name = "Walk 46",
                            RegionID = 8,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9125)
                        },
                        new
                        {
                            ID = 47,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9127),
                            Description = "Description for walk 47",
                            LengthInKm = 2.0,
                            Name = "Walk 47",
                            RegionID = 2,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9128)
                        },
                        new
                        {
                            ID = 48,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9130),
                            Description = "Description for walk 48",
                            LengthInKm = 7.0,
                            Name = "Walk 48",
                            RegionID = 1,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9131)
                        },
                        new
                        {
                            ID = 49,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9133),
                            Description = "Description for walk 49",
                            LengthInKm = 14.0,
                            Name = "Walk 49",
                            RegionID = 2,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9133)
                        },
                        new
                        {
                            ID = 50,
                            Created = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9135),
                            Description = "Description for walk 50",
                            LengthInKm = 11.0,
                            Name = "Walk 50",
                            RegionID = 6,
                            Updated = new DateTime(2024, 8, 26, 14, 23, 53, 882, DateTimeKind.Local).AddTicks(9136)
                        });
                });

            modelBuilder.Entity("NZWalksApi.Data.Entities.WalkEntity", b =>
                {
                    b.HasOne("NZWalksApi.Data.Entities.RegionEntity", "Region")
                        .WithMany("Walks")
                        .HasForeignKey("RegionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("NZWalksApi.Data.Entities.RegionEntity", b =>
                {
                    b.Navigation("Walks");
                });
#pragma warning restore 612, 618
        }
    }
}
