// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalksApi.Data;

#nullable disable

namespace NZWalksApi.Data.Migrations
{
    [DbContext(typeof(NZWalksDBContext))]
    [Migration("20240826131822_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalksApi.Data.Entities.BeautyGradeEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("BeautyGrades");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Awful",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SlightlyDirty",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Normal",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pretty",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MrPropreClean",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NZWalksApi.Data.Entities.RegionEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BeautyGrade")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("I")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BeautyGrade = 5,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(1976),
                            Description = "Description for region 1",
                            I = 0,
                            Name = "Region 1",
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2035)
                        },
                        new
                        {
                            ID = 2,
                            BeautyGrade = 4,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2041),
                            Description = "Description for region 2",
                            I = 0,
                            Name = "Region 2",
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2043)
                        },
                        new
                        {
                            ID = 3,
                            BeautyGrade = 5,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2045),
                            Description = "Description for region 3",
                            I = 0,
                            Name = "Region 3",
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2046)
                        },
                        new
                        {
                            ID = 4,
                            BeautyGrade = 2,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2049),
                            Description = "Description for region 4",
                            I = 0,
                            Name = "Region 4",
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2050)
                        },
                        new
                        {
                            ID = 5,
                            BeautyGrade = 5,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2053),
                            Description = "Description for region 5",
                            I = 0,
                            Name = "Region 5",
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2054)
                        },
                        new
                        {
                            ID = 6,
                            BeautyGrade = 2,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2057),
                            Description = "Description for region 6",
                            I = 0,
                            Name = "Region 6",
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2058)
                        },
                        new
                        {
                            ID = 7,
                            BeautyGrade = 0,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2061),
                            Description = "Description for region 7",
                            I = 0,
                            Name = "Region 7",
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2062)
                        },
                        new
                        {
                            ID = 8,
                            BeautyGrade = 5,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2064),
                            Description = "Description for region 8",
                            I = 0,
                            Name = "Region 8",
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2065)
                        },
                        new
                        {
                            ID = 9,
                            BeautyGrade = 1,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2068),
                            Description = "Description for region 9",
                            I = 0,
                            Name = "Region 9",
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2069)
                        },
                        new
                        {
                            ID = 10,
                            BeautyGrade = 2,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2075),
                            Description = "Description for region 10",
                            I = 0,
                            Name = "Region 10",
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2076)
                        });
                });

            modelBuilder.Entity("NZWalksApi.Data.Entities.WalkEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RegionID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("RegionID");

                    b.ToTable("Walks");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2125),
                            Description = "Description for walk 1",
                            LengthInKm = 4.0,
                            Name = "Walk 1",
                            RegionID = 4,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2126)
                        },
                        new
                        {
                            ID = 2,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2131),
                            Description = "Description for walk 2",
                            LengthInKm = 11.0,
                            Name = "Walk 2",
                            RegionID = 1,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2132)
                        },
                        new
                        {
                            ID = 3,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2135),
                            Description = "Description for walk 3",
                            LengthInKm = 4.0,
                            Name = "Walk 3",
                            RegionID = 5,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2136)
                        },
                        new
                        {
                            ID = 4,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2139),
                            Description = "Description for walk 4",
                            LengthInKm = 14.0,
                            Name = "Walk 4",
                            RegionID = 6,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2140)
                        },
                        new
                        {
                            ID = 5,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2142),
                            Description = "Description for walk 5",
                            LengthInKm = 9.0,
                            Name = "Walk 5",
                            RegionID = 8,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2143)
                        },
                        new
                        {
                            ID = 6,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2147),
                            Description = "Description for walk 6",
                            LengthInKm = 12.0,
                            Name = "Walk 6",
                            RegionID = 8,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2148)
                        },
                        new
                        {
                            ID = 7,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2151),
                            Description = "Description for walk 7",
                            LengthInKm = 9.0,
                            Name = "Walk 7",
                            RegionID = 9,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2152)
                        },
                        new
                        {
                            ID = 8,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2154),
                            Description = "Description for walk 8",
                            LengthInKm = 4.0,
                            Name = "Walk 8",
                            RegionID = 8,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2155)
                        },
                        new
                        {
                            ID = 9,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2158),
                            Description = "Description for walk 9",
                            LengthInKm = 3.0,
                            Name = "Walk 9",
                            RegionID = 7,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2159)
                        },
                        new
                        {
                            ID = 10,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2163),
                            Description = "Description for walk 10",
                            LengthInKm = 8.0,
                            Name = "Walk 10",
                            RegionID = 1,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2164)
                        },
                        new
                        {
                            ID = 11,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2166),
                            Description = "Description for walk 11",
                            LengthInKm = 3.0,
                            Name = "Walk 11",
                            RegionID = 4,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2167)
                        },
                        new
                        {
                            ID = 12,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2170),
                            Description = "Description for walk 12",
                            LengthInKm = 5.0,
                            Name = "Walk 12",
                            RegionID = 1,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2171)
                        },
                        new
                        {
                            ID = 13,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2173),
                            Description = "Description for walk 13",
                            LengthInKm = 5.0,
                            Name = "Walk 13",
                            RegionID = 7,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2174)
                        },
                        new
                        {
                            ID = 14,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2176),
                            Description = "Description for walk 14",
                            LengthInKm = 17.0,
                            Name = "Walk 14",
                            RegionID = 5,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2177)
                        },
                        new
                        {
                            ID = 15,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2180),
                            Description = "Description for walk 15",
                            LengthInKm = 7.0,
                            Name = "Walk 15",
                            RegionID = 3,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2181)
                        },
                        new
                        {
                            ID = 16,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2183),
                            Description = "Description for walk 16",
                            LengthInKm = 14.0,
                            Name = "Walk 16",
                            RegionID = 6,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2184)
                        },
                        new
                        {
                            ID = 17,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2187),
                            Description = "Description for walk 17",
                            LengthInKm = 8.0,
                            Name = "Walk 17",
                            RegionID = 8,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2188)
                        },
                        new
                        {
                            ID = 18,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2224),
                            Description = "Description for walk 18",
                            LengthInKm = 5.0,
                            Name = "Walk 18",
                            RegionID = 1,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2226)
                        },
                        new
                        {
                            ID = 19,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2228),
                            Description = "Description for walk 19",
                            LengthInKm = 17.0,
                            Name = "Walk 19",
                            RegionID = 1,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2229)
                        },
                        new
                        {
                            ID = 20,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2232),
                            Description = "Description for walk 20",
                            LengthInKm = 20.0,
                            Name = "Walk 20",
                            RegionID = 9,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2233)
                        },
                        new
                        {
                            ID = 21,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2235),
                            Description = "Description for walk 21",
                            LengthInKm = 18.0,
                            Name = "Walk 21",
                            RegionID = 5,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2237)
                        },
                        new
                        {
                            ID = 22,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2239),
                            Description = "Description for walk 22",
                            LengthInKm = 7.0,
                            Name = "Walk 22",
                            RegionID = 1,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2240)
                        },
                        new
                        {
                            ID = 23,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2242),
                            Description = "Description for walk 23",
                            LengthInKm = 11.0,
                            Name = "Walk 23",
                            RegionID = 10,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2243)
                        },
                        new
                        {
                            ID = 24,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2245),
                            Description = "Description for walk 24",
                            LengthInKm = 11.0,
                            Name = "Walk 24",
                            RegionID = 2,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2246)
                        },
                        new
                        {
                            ID = 25,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2249),
                            Description = "Description for walk 25",
                            LengthInKm = 10.0,
                            Name = "Walk 25",
                            RegionID = 4,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2250)
                        },
                        new
                        {
                            ID = 26,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2252),
                            Description = "Description for walk 26",
                            LengthInKm = 7.0,
                            Name = "Walk 26",
                            RegionID = 5,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2253)
                        },
                        new
                        {
                            ID = 27,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2256),
                            Description = "Description for walk 27",
                            LengthInKm = 9.0,
                            Name = "Walk 27",
                            RegionID = 8,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2257)
                        },
                        new
                        {
                            ID = 28,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2259),
                            Description = "Description for walk 28",
                            LengthInKm = 14.0,
                            Name = "Walk 28",
                            RegionID = 4,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2260)
                        },
                        new
                        {
                            ID = 29,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2263),
                            Description = "Description for walk 29",
                            LengthInKm = 12.0,
                            Name = "Walk 29",
                            RegionID = 8,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2264)
                        },
                        new
                        {
                            ID = 30,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2266),
                            Description = "Description for walk 30",
                            LengthInKm = 11.0,
                            Name = "Walk 30",
                            RegionID = 10,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2267)
                        },
                        new
                        {
                            ID = 31,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2269),
                            Description = "Description for walk 31",
                            LengthInKm = 14.0,
                            Name = "Walk 31",
                            RegionID = 6,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2270)
                        },
                        new
                        {
                            ID = 32,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2273),
                            Description = "Description for walk 32",
                            LengthInKm = 12.0,
                            Name = "Walk 32",
                            RegionID = 5,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2274)
                        },
                        new
                        {
                            ID = 33,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2276),
                            Description = "Description for walk 33",
                            LengthInKm = 12.0,
                            Name = "Walk 33",
                            RegionID = 5,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2277)
                        },
                        new
                        {
                            ID = 34,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2282),
                            Description = "Description for walk 34",
                            LengthInKm = 18.0,
                            Name = "Walk 34",
                            RegionID = 6,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2283)
                        },
                        new
                        {
                            ID = 35,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2285),
                            Description = "Description for walk 35",
                            LengthInKm = 20.0,
                            Name = "Walk 35",
                            RegionID = 5,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2286)
                        },
                        new
                        {
                            ID = 36,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2288),
                            Description = "Description for walk 36",
                            LengthInKm = 19.0,
                            Name = "Walk 36",
                            RegionID = 10,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2289)
                        },
                        new
                        {
                            ID = 37,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2292),
                            Description = "Description for walk 37",
                            LengthInKm = 12.0,
                            Name = "Walk 37",
                            RegionID = 6,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2293)
                        },
                        new
                        {
                            ID = 38,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2295),
                            Description = "Description for walk 38",
                            LengthInKm = 10.0,
                            Name = "Walk 38",
                            RegionID = 6,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2296)
                        },
                        new
                        {
                            ID = 39,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2298),
                            Description = "Description for walk 39",
                            LengthInKm = 13.0,
                            Name = "Walk 39",
                            RegionID = 6,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2299)
                        },
                        new
                        {
                            ID = 40,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2302),
                            Description = "Description for walk 40",
                            LengthInKm = 6.0,
                            Name = "Walk 40",
                            RegionID = 7,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2303)
                        },
                        new
                        {
                            ID = 41,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2305),
                            Description = "Description for walk 41",
                            LengthInKm = 7.0,
                            Name = "Walk 41",
                            RegionID = 8,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2306)
                        },
                        new
                        {
                            ID = 42,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2309),
                            Description = "Description for walk 42",
                            LengthInKm = 20.0,
                            Name = "Walk 42",
                            RegionID = 7,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2310)
                        },
                        new
                        {
                            ID = 43,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2312),
                            Description = "Description for walk 43",
                            LengthInKm = 14.0,
                            Name = "Walk 43",
                            RegionID = 7,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2313)
                        },
                        new
                        {
                            ID = 44,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2315),
                            Description = "Description for walk 44",
                            LengthInKm = 3.0,
                            Name = "Walk 44",
                            RegionID = 6,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2316)
                        },
                        new
                        {
                            ID = 45,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2319),
                            Description = "Description for walk 45",
                            LengthInKm = 14.0,
                            Name = "Walk 45",
                            RegionID = 2,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2320)
                        },
                        new
                        {
                            ID = 46,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2322),
                            Description = "Description for walk 46",
                            LengthInKm = 6.0,
                            Name = "Walk 46",
                            RegionID = 8,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2323)
                        },
                        new
                        {
                            ID = 47,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2325),
                            Description = "Description for walk 47",
                            LengthInKm = 3.0,
                            Name = "Walk 47",
                            RegionID = 10,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2326)
                        },
                        new
                        {
                            ID = 48,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2330),
                            Description = "Description for walk 48",
                            LengthInKm = 15.0,
                            Name = "Walk 48",
                            RegionID = 8,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2331)
                        },
                        new
                        {
                            ID = 49,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2333),
                            Description = "Description for walk 49",
                            LengthInKm = 9.0,
                            Name = "Walk 49",
                            RegionID = 8,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2334)
                        },
                        new
                        {
                            ID = 50,
                            Created = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2336),
                            Description = "Description for walk 50",
                            LengthInKm = 20.0,
                            Name = "Walk 50",
                            RegionID = 1,
                            Updated = new DateTime(2024, 8, 26, 15, 18, 22, 412, DateTimeKind.Local).AddTicks(2337)
                        });
                });

            modelBuilder.Entity("NZWalksApi.Data.Entities.WalkEntity", b =>
                {
                    b.HasOne("NZWalksApi.Data.Entities.RegionEntity", "Region")
                        .WithMany("Walks")
                        .HasForeignKey("RegionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("NZWalksApi.Data.Entities.RegionEntity", b =>
                {
                    b.Navigation("Walks");
                });
#pragma warning restore 612, 618
        }
    }
}
